jobs:
  print-messages:
    runs-on: ubuntu-latest
    steps:
    - name:    
      run: echo "Hello, World!"
    - name:
      run: echo "Goodbye, World!"

jobs:
  pull-repository:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        repository: 'https://github.com'
