name: jenkins63
on:
  schedule:
  - cron: 48 0-5 * * *
  # The following PollSCM schedule was transformed and may behave differently than in Jenkins.
  # In Actions, this workflow will run on this schedule regardless of any changes whereas in Jenkins a job will only run if there are changes.
  - cron: 38 * * * *
env:
  deploymentBranch: master
  mavenExecutable: mvn-jdk8
jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: sh
      shell: bash
      run: "${{ env.mavenExecutable }} clean compile test-compile"
  Unit_Tests:
    name: Unit-Tests
    runs-on: ubuntu-latest
    needs: Compile
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: sh
      shell: bash
      run: "${{ env.mavenExecutable }} surefire:test"
  Integration_Tests:
    name: Integration-Tests
    runs-on: ubuntu-latest
    needs: Unit_Tests
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: sh
      shell: bash
      run: "${{ env.mavenExecutable }} failsafe:integration-test failsafe:verify"
  Release:
    if: github.ref == 'refs/heads/"${{ env.deploymentBranch }}"'
    runs-on: ubuntu-latest
    needs: Integration_Tests
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: sh
      shell: bash
      run: "${{ env.mavenExecutable }} clean deploy -Dmaven.test.skip=true"
  SonarQube:
    if: github.ref == 'refs/heads/"${{ env.deploymentBranch }}"'
    runs-on: ubuntu-latest
    needs: Release
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: sh
      shell: bash
      run: "${{ env.mavenExecutable }} clean verify sonar:sonar -Dsonar.host.url=http://sonarqube.avidesmedia/"
  POM_Analysis:
    if: github.ref == 'refs/heads/"${{ env.deploymentBranch }}"'
    name: POM-Analysis
    runs-on: ubuntu-latest
    needs: SonarQube
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: sh
      shell: bash
      run: "${{ env.mavenExecutable }} enforcer:enforce"
