name: jenkins16
on:
  workflow_dispatch:
    inputs:
      NOTIFY_CHANNEL:
        required: false
        description: Slack channel to send notifications to.
        default: "#ci-notification"
      TAG:
        required: false
        description: A specific sha or branch to build.
        default: master
env:
#   # This item has no matching transformer
#   BLUE_URL: '"${{ env.JENKINS_URL }}blue/organizations/jenkins/${{ env.JOB_NAME }}/detail/${{ env.JOB_NAME }}/${{ env.BUILD_NUMBER }}/pipeline"'
defaults:
  run:
    working-directory: '"${{ env.JOB_NAME }}/${{ env.BUILD_NUMBER }}"'
jobs:
  Checkout:
    runs-on:
      - self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: sh
      shell: bash
      run: git checkout $TAG
  TestUnit:
    runs-on:
      - self-hosted
    needs: Checkout
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: sh
      shell: bash
      run: "./bin/test"
    - name: snapshot post build job status
      run: echo "failure=${{ job.status == 'failure' }}" >> $GITHUB_OUTPUT
      id: post_build
#     # This item has no matching transformer
#     - slackBuildFailure:
#         isLiteral: true
#         value: TestUnit
#       if: steps.post_build.outputs.failure == 'true'
  Post-Build:
    if: always()
    name: Post Build
    runs-on:
      - self-hosted
    needs:
    - Checkout
    - TestUnit
    steps:
    - name: snapshot post build workflow status
      run: |-
        echo "aborted=${{ contains(needs.*.result,'cancelled') }}" >> $GITHUB_OUTPUT
        echo "success=${{ contains(needs.*.result,'success') && !contains(needs.*.result,'cancelled') && !contains(needs.*.result,'failure') }}" >> $GITHUB_OUTPUT
        echo "failure=${{ contains(needs.*.result,'failure') && !contains(needs.*.result,'cancelled') }}" >> $GITHUB_OUTPUT
      id: post_build
    - name: delete directory
      shell: bash
      run: rm -rf "`pwd`"
      if: steps.post_build.outputs.failure == 'true'
    - name: delete directory
      shell: bash
      run: rm -rf "`pwd`"
      if: steps.post_build.outputs.aborted == 'true'
    - name: delete directory
      shell: bash
      run: rm -rf "`pwd`"
      if: steps.post_build.outputs.success == 'true'
