name: test2
on:
  workflow_dispatch:
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Access output files
      run: |
        cat $GITHUB_WORKSPACE/output/audit_summary.md || echo "File not found"
  Stage2:
    runs-on: ubuntu-latest
    needs: Hello
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: List all files in workspace
      run: |
        echo "Current workspace: $GITHUB_WORKSPACE"
        ls -R $GITHUB_WORKSPACE
  Stage3:
    runs-on: ubuntu-latest
    needs: Stage2
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: List files in default workspace
      run: ls -al $GITHUB_WORKSPACE
