name: test2
on:
  workflow_dispatch:
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: "echo è¿\x99æ\x98¯ä¸\x80ä¸ªæµ\x8Bè¯\x95"
  Stage2:
    runs-on: ubuntu-latest
    needs: Hello
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: "echo ç¬¬äº\x8Cé\x98¶æ®µ"
  Stage3:
    runs-on: ubuntu-latest
    needs: Stage2
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: "echo ç¬¬ä¸\x89é\x98¶æ®µ"
    - name: List files in default workspace
      run: ls -al $GITHUB_WORKSPACE
