name: test5
on:
  workflow_dispatch:
jobs:
  Build_and_Test_Module_A:
    name: Build and Test Module A
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: sh
      shell: bash
      run: npm install
      working-directory: module-a
    - name: sh
      shell: bash
      run: npm test
      working-directory: module-a
  Build_and_Test_Module_B:
    name: Build and Test Module B
    runs-on: ubuntu-latest
    needs: Build_and_Test_Module_A
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: sh
      shell: bash
      run: npm install
      working-directory: module-b
    - name: sh
      shell: bash
      run: npm test
      working-directory: module-b
